apiVersion: apps/v1
kind: Deployment
metadata:
  name: dish-search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dish-search-service
  template:
    metadata:
      labels:
        app: dish-search-service
    spec:
      containers:
      - name: dish-search-service
        image: ug2002/onlinefooddelivery-dish_search:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dish-search-service
spec:
  type: NodePort
  selector:
    app: dish-search-service
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32296
