apiVersion: v1
kind: Service
metadata:
  name: dish-search-service
spec:
  type: NodePort
  selector:
    app: dish-search-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001  # Specify a NodePort or let Kubernetes assign one
