# order-booking-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-booking-service
  template:
    metadata:
      labels:
        app: order-booking-service
    spec:
      containers:
      - name: order-booking-service
        image: ug2002/onlinefooddelivery-order_booking:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: order-booking-service
spec:
  type: NodePort
  selector:
    app: order-booking-service
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32541
