apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-cancellation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-cancellation-service
  template:
    metadata:
      labels:
        app: order-cancellation-service
    spec:
      containers:
        - name: order-cancellation-service
          image: ug2002/onlinefooddelivery-order_cancellation:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: order-cancellation-service
spec:
  selector:
    app: order-cancellation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
